region: eu-central-1
vpc:
  securityGroupIds:
    - sg-12345678
  subnetIds:
    - subnet-12345678
    - subnet-12345678

# Environment variables accessible in NodeJS via env.process.XXX
ENVIRONMENT:
  # Debugging
  LOG_LEVEL: debug # info

  # Serverless base settings
  SERVERLESS_AWS_ACCOUNT_ID: "123456789012"
  SERVERLESS_STAGE: ${opt:stage, self:provider.stage}
  SERVERLESS_PROJECT: ${self:service}
  SERVERLESS_REGION: ${opt:region, self:provider.region}

 # Redis config
  #REDIS_HOST: abcde.ciziue.0001.euc1.cache.amazonaws.com
  #REDIS_PORT: '6379'
  #REDIS_PREFIX: aa-data

# SNS settings
  #SNS_ARN_AGGREGATIONS: arn:aws:sns:${self:provider.region}:123456789012:${self:custom.prefix}-AggregationsTopic
  #SNS_ARN_RICH_DATA: arn:aws:sns:${self:provider.region}:123456789012:${self:custom.prefix}-RichDataTopic
