# Environment variables accessible in NodeJS via env.process.XXX
ENVIRONMENT:
  # Debugging
  LOG_LEVEL: debug

  # Serverless base settings
  SERVERLESS_AWS_ACCOUNT_ID: "134856371062"
  SERVERLESS_STAGE: ${opt:stage, self:provider.stage}
  SERVERLESS_PROJECT: ${self:service}
  SERVERLESS_REGION: ${opt:region, self:provider.region}
